summary:
  id: 'vue'
  title: 'Vue.js'
  subtitle: 'Framework Frontend Progressif'
  description: "Construisez des interfaces utilisateur modernes et réactives. Apprenez le framework progressif, la gestion d'état avec Pinia, et créez des composants réutilisables et maintenables."
  icon: 'i-simple-icons-vuedotjs'
  to: '/vue'
  gradient: 'from-emerald-500 to-teal-700'
  image: '/images/landing/vue-browser.png'
  keyPoints:
    - 'Créer des composants réutilisables avec la Composition API'
    - 'Utiliser Naive UI comme design system professionnel'
    - 'Gérer l''état global de l''application avec Pinia'
    - 'Connecter votre application à une API REST backend'
    - 'Implémenter la navigation avec Vue Router dans une SPA'

usefulLinks:
  - label: 'Télécharger Node JS'
    icon: 'i-heroicons-cube-transparent'
    to: 'https://vuejs.org/guide/introduction'
    target: '_blank'
  - label: 'Doc Vue JS'
    icon: 'i-heroicons-squares-2x2'
    to: 'https://vuejs.org/guide/introduction'
    target: '_blank'
  - label: 'Doc TypeScript'
    icon: 'i-heroicons-code-bracket'
    to: 'https://www.typescriptlang.org/docs/'
    target: '_blank'
  - label: 'Doc Pinia'
    icon: 'i-heroicons-square-3-stack-3d'
    to: 'https://pinia.vuejs.org/getting-started.html'
    target: '_blank'
  - label: 'Composant Naive UI'
    icon: 'i-heroicons-puzzle-piece'
    to: 'https://www.naiveui.com/en-US/os-theme/components/button'
    target: '_blank'
  - label: 'Doc VueRouter'
    icon: 'i-heroicons-map'
    to: 'https://next.router.vuejs.org/'
    target: '_blank'
  - label: 'Doc Cypress'
    icon: 'i-heroicons-beaker'
    to: 'https://docs.cypress.io/app/get-started/why-cypress'
    target: '_blank'

exercises:
  - label: 'Corrigé du cours'
    icon: 'i-heroicons-academic-cap'
    target: '_blank'
    to: 'https://github.com/vfourny/vuejs-tutorial'
  - label: 'Pokemon TCG'
    icon: 'i-heroicons-ellipsis-horizontal-circle'
    target: '_blank'
    to: 'https://classroom.github.com/a/1KxZ1YjF'
