summary:
  id: 'git'
  title: 'Git'
  subtitle: 'Versioning & Collaboration'
  description: 'Maîtrisez le versioning de code et la collaboration en équipe avec Git et GitHub. Gérez vos branches efficacement, résolvez les conflits, et adoptez les meilleures pratiques professionnelles.'
  icon: 'i-simple-icons-git'
  to: '/git'
  gradient: 'from-orange-500 to-red-700'
  image: '/images/landing/git-workflow.png'
  keyPoints:
    - 'Maîtriser les commandes Git essentielles (add, commit, push, pull)'
    - 'Créer et gérer des repositories sur GitHub'
    - 'Travailler avec les branches et gérer les conflits'
    - 'Comprendre merge vs rebase pour une meilleure collaboration'
    - 'Adopter des workflows professionnels en équipe'

usefulLinks:
  - label: 'Télécharger GIT'
    icon: 'i-heroicons-arrow-down-tray'
    to: 'https://git-scm.com/downloads'
    target: '_blank'
  - label: 'Documentation officielle GIT'
    icon: 'i-heroicons-book-open'
    to: 'https://git-scm.com/doc'
    target: '_blank'
  - label: 'GitHub'
    icon: 'i-simple-icons-github'
    to: 'https://github.com'
    target: '_blank'
  - label: 'Documentation GitHub'
    icon: 'i-heroicons-book-open'
    to: 'https://docs.github.com/fr'
    target: '_blank'
  - label: 'Aide-mémoire Git'
    icon: 'i-heroicons-document-text'
    to: 'https://education.github.com/git-cheat-sheet-education.pdf'
    target: '_blank'

exercises:
  - label: 'Apprendre Git (Interactif)'
    icon: 'i-heroicons-academic-cap'
    to: 'https://learngitbranching.js.org/?locale=fr'
    target: '_blank'
