summary:
  id: 'node'
  title: 'Node.js'
  subtitle: 'Développement Backend & APIs'
  description: "Développez des applications backend performantes et scalables. Maîtrisez JavaScript côté serveur, créez des APIs REST robustes, et gérez l'asynchrone avec Node.js."
  icon: 'i-simple-icons-nodedotjs'
  to: '/node'
  gradient: 'from-green-500 to-green-700'
  image: '/images/landing/node-terminal.png'
  keyPoints:
    - 'Développer des APIs REST avec Express et TypeScript'
    - 'Gérer une base de données avec Prisma ORM'
    - 'Implémenter l''authentification JWT et sécuriser vos APIs'
    - 'Documenter vos APIs avec Swagger/OpenAPI et tester avec Vitest'
    - 'Créer des applications temps réel avec Socket.IO'

usefulLinks:
  - label: 'Télécharger Node.js'
    icon: 'mdi:nodejs'
    to: 'https://nodejs.org/fr/'
    target: '_blank'
  - label: 'Télécharger NVM'
    icon: 'mdi:source-branch'
    to: 'https://github.com/nvm-sh/nvm'
    target: '_blank'
  - label: 'Doc Node.js'
    icon: 'mdi:book-open-variant'
    to: 'https://nodejs.org/docs/latest/api/'
    target: '_blank'
  - label: 'Doc TypeScript'
    icon: 'mdi:language-typescript'
    to: 'https://www.typescriptlang.org/docs/'
    target: '_blank'
  - label: 'Doc Express'
    icon: 'simple-icons:express'
    to: 'https://expressjs.com/fr/'
    target: '_blank'
  - label: 'Télécharger Bruno'
    icon: 'mdi:dog'
    to: 'https://www.usebruno.com/downloads'
    target: '_blank'
  - label: 'Doc Prisma'
    icon: 'simple-icons:prisma'
    to: 'https://www.prisma.io/docs/'
    target: '_blank'
  - label: 'Doc Vitest'
    icon: 'simple-icons:vitest'
    to: 'https://vitest.dev/guide/'
    target: '_blank'
  - label: 'Doc JWT'
    icon: 'mdi:key-variant'
    to: 'https://jwt.io/introduction'
    target: '_blank'
  - label: 'Swagger UI'
    icon: 'mdi:api'
    to: 'https://swagger.io/tools/swagger-ui/'
    target: '_blank'
  - label: 'Swagger Editor'
    icon: 'mdi:pencil-box-outline'
    to: 'https://editor.swagger.io/'
    target: '_blank'
  - label: 'Doc Socket.IO'
    icon: 'simple-icons:socketdotio'
    to: 'https://socket.io/docs/'
    target: '_blank'

exercises:
  - label: 'Corrigé du cours'
    icon: 'mdi:school'
    target: '_blank'
    to: 'https://github.com/vfourny/nodejs-courses/tree/main'
  - label: 'API Pokémon'
    icon: 'mdi:pokeball'
    target: '_blank'
    to: 'https://classroom.github.com/a/1kY2YdAF'
